# Generated by Django 3.1.6 on 2021-02-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210204_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='client_name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='fund_name',
            new_name='fund',
        ),
    ]
