# Generated by Django 3.1.6 on 2021-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210218_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_to_complete',
            field=models.FloatField(default=1),
        ),
    ]
