# Generated by Django 3.1.6 on 2021-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210218_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_advancement',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to_complete',
            field=models.FloatField(),
        ),
    ]
